name: ðŸŒ Ping Glitch Site

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:       # Allow manual runs

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ”” Ping Glitch Site
        run: |
          curl -s https://pnbagent.glitch.me > /dev/null
